---
    name: CI Tests

    on:  # yamllint disable-line rule:truthy
      workflow_dispatch:
      push:
        branches:
        - main
      pull_request:
        branches:
        - main

    jobs:
      test:
        name: test
        runs-on: ubuntu-latest
        steps:
        - name: Run Unit Tests
          run: make docker/test
